name: Generate
description: Code generation
runs:
  steps:
    - name: Generate
      shell: bash
      run: ./gradlew generate
    - name: Diff
      id: diff
      shell: bash
      run: git diff --quiet ./uds/library/src || echo "changed=true" >> "$GITHUB_OUTPUT"
    - name: Commit
      shell: bash
      if: steps.diff.outputs.changed == 'true'
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "Update generated files"
        git push