name: Generate
description: Code generation
runs:
  using: "composite"
  steps:
    - name: Changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
          - 'trigger.txt'
    - name: Generate
      if: steps.changes.outputs.src == 'true'
      shell: bash
      run: ./gradlew generate
    - name: Diff
      id: diff
      shell: bash
      run: git diff --quiet ./uds/library/src || echo "changed=true" >> "$GITHUB_OUTPUT"
#    - name: Commit
#      shell: bash
#      if: steps.diff.outputs.changed == 'true'
#      run: |
#        git config --global user.name "${GITHUB_ACTOR}"
#        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#        git add .
#        git commit -m "Update generated files"
#        git push
